site_name: polars_ta API References
site_url: https://polars-ta.readthedocs.io/en/latest/

nav:
  - Home: index.md
  - polars_ta.wq:
      - wq/arithmetic.md
      - wq/cross_sectional.md
      - wq/logical.md
      - wq/preprocess.md
      - wq/time_series.md
      - wq/transformational.md
      - wq/vector.md
  - polars_ta.ta:
      - ta/momentum.md
      - ta/operators.md
      - ta/overlap.md
      - ta/price.md
      - ta/statistic.md
      - ta/transform.md
      - ta/volatility.md
      - ta/volume.md
  - polars_ta.tdx:
      - tdx/arithmetic.md
  - polars_ta.talib: talib/index.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy

strict: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ . ]
          options:
            summary: true
            show_root_heading: true
            show_if_no_docstring: true
            show_source: true
            show_signature_annotations: true
            docstring_style: numpy