site_name: polars_ta API References
site_url: https://polars-ta.readthedocs.io/en/latest/

nav:
  - Home: index.md
  - polars_ta.wq:
      - wq/arithmetic.md
      - wq/cross_sectional.md
      - wq/logical.md
      - wq/preprocess.md
      - wq/time_series.md
      - wq/transformational.md
      - wq/vector.md
  - polars_ta.ta:
      - ta/index.md
      - ta/momentum.md
      - ta/operators.md
      - ta/overlap.md
      - ta/price.md
      - ta/statistic.md
      - ta/transform.md
      - ta/volatility.md
      - ta/volume.md
  - polars_ta.tdx:
      - tdx/arithmetic.md
      - tdx/choice.md
      - tdx/energy.md
      - tdx/logical.md
      - tdx/moving_average.md
      - tdx/over_bought_over_sold.md
      - tdx/pattern.md
      - tdx/pattern_feature.md
      - tdx/pressure_support.md
      - tdx/reference.md
      - tdx/statistic.md
      - tdx/trend.md
      - tdx/trend_feature.md
      - tdx/volume.md
  - polars_ta.talib: talib/index.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy

strict: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ . ]
          options:
            summary: true
            show_root_heading: true
            show_if_no_docstring: true
            show_source: false
            show_signature_annotations: true
            docstring_style: numpy
  - llmstxt:
      full_output: llms-full.txt
      sections:
        Usage documentation:
          - index.md
          - wq/*.md
          - ta/*.md
          - tdx/*.md
          - talib/*.md

